### ISSUE TITLE
Include 2018 surveys in this version?

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfsynopsis#108]
Maria just sent around notification that the WCVI and WCHG 2018 surveys are now in the databases. Should we update the plots to include the newest survey data at this stage or wait for next year because this is the version that was reviewed? Unfortunately, I don't think we discussed this exact situation at the meeting.

**Comment by elisekeppel** [comment]
At the meeting we did discuss timing of release and when the data are usually included by. I think the understanding was that future updates would happen early in the calendar year and summarize the up to the end of the previous year.

I'd say include all the available data when we're done with all the edits for the most up-to-date product and include the date of final extraction in the document.

**Comment by seananderson** [comment]
Done
