### ISSUE TITLE
Consider some very low threshold for showing the IPHC index (or explain anomalies)

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfsynopsis#116]
E.g. from CR: greenstriped rockfish creates a bizarre seesaw pattern because of 4 years with single observations (I assume) with the rest at zero.

**Comment by andrew-edwards** [comment]
1. Best to add an explanation in the appendix (as can then refer back to a couple of example figures).

2. Okay if I get caught up through github, do some editing, but don't rebuild it (busy with hake still). I think only a few minor text edits so I shouldn't screw anything up (ha ha)?

**Comment by seananderson** [comment]
1. sure

2. Yes, read and edit the .Rmd files directly. There has been some more editing since the PDF I last sent.

**Comment by andrew-edwards** [comment]
Done and done. Three commits (plus fixing a conflict - double check it's good, should be).

Could you please just check the rendering in the .pdf of the commits, as I haven't built (makes me nervous when I do that!). Think I got the .Rmd links okay. Thanks.
