### ISSUE TITLE
Redstripe was assessed

### ISSUE THREAD

**Issue by cgrandin** [pbs-assess/gfsynopsis#128]
Redstripe Rockfish was assessed last fall. The SAR may not have been updated in the synopsis yet and the date should be 2018 (https://waves-vagues.dfo-mpo.gc.ca/Library/40738644.pdf).

**Comment by seananderson** [comment]
Thanks, fixed: https://github.com/pbs-assess/gfsynopsis/commit/d2a6addd831131e3df8340c913341e4e94eecec0
