### ISSUE TITLE
Cannot build doc - error: synoptic_grid is not an exported object from gfplot

### ISSUE THREAD

**Issue by elisekeppel** [pbs-assess/gfsynopsis#129]
Not sure how to export an object which isn't a function where Roxygen does the Namespace building for me...

**Comment by seananderson** [comment]
Should be there, but you'll need to install the latest gfplot.

Doesn't need to be exported in roxygen.

```r
usethis::use_data(synoptic_grid, internal = FALSE, overwrite = TRUE)
```

and `LazyData: true` is enough.
