### ISSUE TITLE
Manuscript - worth mentioning how the synopsis evolved from the Tiered Approach?

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/gfsynopsis#131]
The 'Tiered Approach' idea is used elsewhere, so it might demonstrate the broader appeal of the synopsis approach. (The TOR for gfsynopsis meeting mentions this; would probably just have to ref either the Tiered Approach meeting Proceedings or gfsynopsis ones, and maybe a Tiered Approach ref if space).

I can take a stab at it.

**Comment by seananderson** [comment]
Not sure we have space to get into it. The MP framework is more a direct evolution of the tiered approach. If we haven't mentioned it, though, we should mention how helpful it is to get an idea of what assessment models or management procedures are applicable for a given stock.
