### ISSUE TITLE
Fig G.4 (e.g. 2006) is now different to submitted version

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/gfsynopsis#137]
Two plots/datasets that should be the same:

A. Submitted version (15 Nov 18) of report has Fig G.4 panel (year) 2006 with highest values in first bin. I have a `hook-with-bait.rds` file from October 2018 that gives the same result.

B. Current version (25 Sep 19) has 2006 with highest values in 4th bin.

1. Could it be the change to `gfiphc`? No - I used the `gfplot` version before functions were migrated to `gfiphc` (22 Mar 2019) and this gives B. For `gfplot`:
```
git co 591ccb05b
```
gives in R:
```
> y <-  get_all_iphc_set_counts("hook with bait")
> mar22 <-  dplyr::filter(y, year == 2006)
> mar22
# A tibble: 170 x 11
    year station   lat   lon  E_it  N_it   C_it E_it20 N_it20 C_it20 usable
   <dbl> <chr>   <dbl> <dbl> <dbl> <dbl>  <dbl>  <dbl>  <dbl>  <dbl> <chr> 
 1  2006 2007     48.7 -125.  6.08   231 38.0     1.21     40 32.9   Y     
 2  2006 2008     48.7 -125.  6.02   175 29.1     1.20     35 29.1   Y     
 3  2006 2003     48.5 -125.  6.02     2  0.332   1.20      0  0     Y     
 4  2006 2002     48.3 -126.  5.07     6  1.18    1.22      4  3.28  N     
 5  2006 2001     48.3 -126.  6.02     3  0.498   1.21      2  1.65  Y     
 6  2006 2004     48.5 -126.  6.02     2  0.332   1.20      1  0.832 Y     
 7  2006 2005     48.5 -126.  6.08     7  1.15    1.22      1  0.816 Y     
 8  2006 2006     48.5 -126.  6.02     2  0.332   1.21      0  0     Y     
 9  2006 2011     48.7 -126.  6.02     2  0.332   1.20      2  1.66  Y     
10  2006 2010     48.7 -126.  6.02     7  1.16    1.22      2  1.64  Y     
# ... with 160 more rows
```
and the plot is same as Sean's (B) when doing the full
```
ggplot(data=y,
          aes(N_it) ) +
          xlab("Number of hooks returned with bait in each set") +
          ylab("Frequency (number of sets)") +
          geom_histogram() +
          facet_wrap(. ~ year, ncol=4)
```

Also tried checking out the `gfplot` version just before submission  (19 Nov 2018): 
```
git co 23729fda73
```
which gives
```
> y <- get_all_iphc_set_counts("hook with bait")
> nov18 <-  dplyr::filter(y, year == 2006)
> nov18
# A tibble: 170 x 11
    year station   lat   lon  E_it  N_it   C_it E_it20 N_it20 C_it20 usable
   <dbl> <chr>   <dbl> <dbl> <dbl> <dbl>  <dbl>  <dbl>  <dbl>  <dbl> <chr> 
 1  2006 2007     48.7 -125.  6.08    87 14.3     1.21     16  13.2  Y     
 2  2006 2008     48.7 -125.  6.02    27  4.48    1.20      2   1.66 Y     
 3  2006 2003     48.5 -125.  6.02     1  0.166   1.20      0   0    Y     
 4  2006 2002     48.3 -126.  5.07     3  0.592   1.22      2   1.64 N     
 5  2006 2001     48.3 -126.  6.02     0  0       1.21      0   0    Y     
 6  2006 2004     48.5 -126.  6.02     0  0       1.20      0   0    Y     
 7  2006 2005     48.5 -126.  6.08     2  0.329   1.22      0   0    Y     
 8  2006 2006     48.5 -126.  6.02     1  0.166   1.21      0   0    Y     
 9  2006 2011     48.7 -126.  6.02     0  0       1.20      0   0    Y     
10  2006 2010     48.7 -126.  6.02     1  0.166   1.22      0   0    Y     
# ... with 160 more rows
```
Can see the first `N_it` is 87, but for B it is 231. Redoing the figures gives A again.

So, it is NOT a change in the database. Will save this and continue...

**Comment by seananderson** [comment]
Did the SQL change at all?

E.g. git blame for `23729fda73`:
https://github.com/pbs-assess/gfplot/blame/591ccb05be541320d534c541292c84cdae396e1a/inst/sql/get-iphc-hook-level-bait-on-hook.sql

**Comment by andrew-edwards** [comment]
Only changes to `gfiphc` R code since the move is just exporting some functions:
https://github.com/pbs-assess/gfiphc/tree/master/R

SQL was my next step ;)

**Comment by andrew-edwards** [comment]
Sean's link above works, which made me wonder if the SQL query was still in `gfplot` and also in `gfiphc`. But no, it is not in `gfplot`.

And the queries in `gfiphc` haven't been dchanged for six months:
https://github.com/pbs-assess/gfiphc/tree/master/inst/sql

I'll double check that each file hasn't changed since the move, then tick this nice box:
- [ ]

**Comment by seananderson** [comment]
It works because it is a git blame for an old commit. Not sure I follow everything above. Did it change before or after the move to gfiphc?

**Comment by andrew-edwards** [comment]
So, the change is in `gfplot` between:
 
A. Version just before submission (19 Nov 2018), 
```
git co 23729fda73
```

and

B. Version just before moving to `gfiphc` (22 Mar 2019):
```
git co 591ccb05b
```

Database hasn't changed, and wasn't caused by migration to `gfiphc`. So I'll next look at blame/history in `gfplot` between those two dates...

**Comment by andrew-edwards** [comment]
`gfplot` commit 0ad9d596  (21 Dec 2018) gives B (=current version).

commit before that is b5cd452c (20 Dec 2018) gives the same - there were some changes to `get_iphc_hooks()`, but it's not those.

**Comment by andrew-edwards** [comment]
So it's between 19 Nov 2018 and 20 Dec 2018.

**Comment by seananderson** [comment]
```

**Comment by seananderson** [comment]
`git log --pretty=format:"%ad - %an: %s" --after="2018-11-19" --until="2018-12-20"`

**Comment by andrew-edwards** [comment]
Think it's this:
https://github.com/pbs-assess/gfplot/commit/ff30d0a049bce5d88f5bbeb47eea199a863c46fd

Kind of remember Elise mentioning including the 'bait skin on hook' code. I'll chat with her...

**Comment by seananderson** [comment]
That's what I was wondering with the git blame link

**Comment by andrew-edwards** [comment]
Conclusion: inclusion of 6 (bait skin on hook) in pbs-assess/gfplot@ff30d0a  counts hooks with bait skin as hooks with bait. Therefore bumps up the numbers of hooks with bait (hooks that are still fishing), hence shifting the histograms in Fig. G.4 to the right.

So undoing that change (now part of `gfiphc`) to stick with what the text says and what was submitted. Something to look into and think about when doing hook competition in detail.

**Comment by andrew-edwards** [comment]
Success. Updating `gfiphc` as per above commit, gives:

```
> y <-  get_all_iphc_set_counts("hook with bait")
> gfiphc_now <-  dplyr::filter(y, year == 2006)
> gfiphc_now
# A tibble: 170 x 11
    year station   lat   lon  E_it  N_it   C_it E_it20 N_it20 C_it20 usable
   <dbl> <chr>   <dbl> <dbl> <dbl> <dbl>  <dbl>  <dbl>  <dbl>  <dbl> <chr> 
 1  2006 2007     48.7 -125.  6.08    87 14.3     1.21     16  13.2  Y     
 2  2006 2008     48.7 -125.  6.02    27  4.48    1.20      2   1.66 Y     
 3  2006 2003     48.5 -125.  6.02     1  0.166   1.20      0   0    Y     
 4  2006 2002     48.3 -126.  5.07     3  0.592   1.22      2   1.64 N     
 5  2006 2001     48.3 -126.  6.02     0  0       1.21      0   0    Y     
 6  2006 2004     48.5 -126.  6.02     0  0       1.20      0   0    Y     
 7  2006 2005     48.5 -126.  6.08     2  0.329   1.22      0   0    Y     
 8  2006 2006     48.5 -126.  6.02     1  0.166   1.21      0   0    Y     
 9  2006 2011     48.7 -126.  6.02     0  0       1.20      0   0    Y     
10  2006 2010     48.7 -126.  6.02     1  0.166   1.22      0   0    Y     
# ... with 160 more rows
```
So `N_it` in the first row is 87, matching the value above for Nov 18, matching the submitted version of `gfsynopsis`. 
And the plot matches the originally submitted one (but now with 2018). Made it!

Not used in the main species plots, but good to have figured out. Will get thought about in more details if someone looks into hook competition.
