### ISSUE TITLE
Add additional species for next report

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfsynopsis#144]
- [ ] Shortbelly Rockfish
- [ ] One that Malcolm mentioned (not in Hart book)

**Comment by andrew-edwards** [comment]
Second one might be Popeye - I saw it mentioned in something the other day, and asked him about it as never heard of it.

**Comment by andrew-edwards** [comment]
Neither Popeye or Shortbelly Rockfish appear in IPHC data, for the record....

**Comment by andrew-edwards** [comment]
The above commit should ensure that Popeye and Shortbelly don't just give errors when importing data from gfiphc (or maybe that's not a problem anyway).
