### ISSUE TITLE
Add to caveats section

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfsynopsis#15]
A running list of things to add:

- [x] these aren't necessarily the best representations of catch and they won't necessarily match reconstructed timeseries in stock assessments
- [x] longline discard weights are not included (and make sure these are all removed)
- [x] Some recent species-specific declines in commercial catch, in particular Bocaccio and Yelloweye, are due to implementation of management measures. Might be worth noting as a caveat in the description of these plots.

**Comment by seananderson** [comment]
@elisekeppel , (re:longline discard weights are not included (and make sure these are all removed))  I think it was on our checklist to check. Can you check what's happening and clarify text as needed? No need to change any code.

**Comment by andrew-edwards** [comment]
@elisekeppel  Can you also double check Fig 13 caption (third line up) - mentions longline discards (I changed 'and discarded' to 'or discarded' earlier
