### ISSUE TITLE
get_data(path="data-cache2/")  is extracting for all species

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/gfsynopsis#30]
`get_data()` has default `type="A"` but it seems to be extracting the type B species also. 

I think it's something to do with `get_spp_names()`. Not a big problem, just worth noting that the default seems to get ignored.

I'm setting `path="data-cache2/"` because that's what appears to be in the `make.R` file that looks to be used. 

Partly documenting this here so I can add it to a `readme` somewhere for future users (i.e. steps to produce the synopsis report), which I couldn't see anywhere obvious (sorry if I missed it). Also, my laptop is going to restart soon and so I want to document my commands.

**Comment by seananderson** [comment]
Yeah, sorry. I discovered that when I accidentally extracted all species last time too. I'd fixed it but hadn't committed or pushed. Just pushed the fix.

There isn't really any documentation right now on how to create the whole synopsis report. I plan to clean the process up a little bit too. Good to have someone else trying, but sorry for the pain at this point.

**Comment by andrew-edwards** [comment]
No worries. Partly why I'm keeping notes (and for my own benefit). Thanks.

**Comment by seananderson** [comment]
You will soon noticed that I haven't updated `make.R` since I changed the output format from `cache_pbs_data()`. There is now one file per species with each species having a list of data frames.

**Comment by seananderson** [comment]
I think I just fixed `make.R` to work with the latest functions. I also updated the `make_pages()` function. Let me know if you try it and by some miracle it works for you.
