### ISSUE TITLE
Would like to build gfsynopsis in next couple of days.

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/gfsynopsis#41]
I think you said you were working some stuff out, and so not to try yet. And that you would give me the model outputs so I don't have to run them, yes?

On #31 it look like I had it building on Aug 13th, apart from a few things that will hopefully get solved when starting over.

I need to put some functions into `gfplot`, but it will be good to use `gfsynopsis` at the same time to check everything.

**Comment by seananderson** [comment]
I can help you get it going tomorrow. Yes, unless you are very patient you will at least want the CPUE standardization model cache files and probably the spatial model fits too. Theoretically everything should be working right now, but I've also switched to csasdown/RMarkdown.

If you want to prepare then run:

```r
devtools::load_all("../gfplot") # for development
devtools::load_all(".")  # for development
dc <- file.path("report", "data-cache")
gfsynopsis::get_data(type = c("A", "B"), path = dc, force = FALSE)
```

with the latest version of both packages assuming that your working directory is the base folder of gfsynopsis.

Note that `gfsynopsis::get_data` will check and not re-download existing species files unless `force = TRUE`. I don't think anything major has happened to the data fetching functions in quite a while.

Note that this is now getting data for all species. Even if you accidentally ran it for all the species that were in there before that was only about a third of the B species.

Another difference is now the species are fetched by species code. I think there are two species where this is important.

**Comment by andrew-edwards** [comment]
Thanks. Will try tomorrow (won't run from home anyway as need GFbio). Though I'll maybe pull and check it builds. Looks like you did lots of tidying up today.

My IPHC code calls the non-GFBio data by species name (converted to slightly different IPHC name when necessary), but I'll look up your conversion thing and incorporate that. I also need to check the Type B species and put in the ones we have. And decide what to do about eelpouts and some other things....

**Comment by andrew-edwards** [comment]
Will carry on tomorrow - got in a mess with installing packages (hadn't closed all my R sessions which can get in a mess)....

**Comment by andrew-edwards** [comment]
Got it building! Had to comment out the main figures, but I get a functioning .pdf. Using the bookdown stuff. Had to manually tweak a few pathnames, but can sort that out tomorrow. 
Pleasantly surprised.

**Comment by andrew-edwards** [comment]
That build above worked - I had to install an earlier version of rstan I think. But today rstan won't install, even using
```
devtools::install_version("rstan", version = "2.17.3")    # or 2.17.2
```
Will try again tomorrow - currently fudging it in gfsynopsis to get it building.

**Comment by andrew-edwards** [comment]
Ooh - version 2.18.1 is the latest on CRAN. That actually installs okay, just with the usual
```
install.packages("rstan")
```

And I've built the document with a few fudges (no Type B for now as I don't have the data from PBS). But it looks good.

**Comment by andrew-edwards** [comment]
Document with figures builds (when I comment out threadfin sculpin onwards - I'll try just skipping that one and building the other maps later).

**Comment by seananderson** [comment]
From googling `gdashmu` it looks like it's coming from here:
https://github.com/cran/msm/blob/master/R/utils.R

But I'm not sure where that's getting called. Maybe in the vB model fits? Would need a traceback() to figure out what function caused that. I'm assuming you have a version of gfplot from sometime today installed?

**Comment by seananderson** [comment]
Oh, ha, it's from my reimplementation: 
https://github.com/pbs-assess/gfplot/blob/master/R/maturity.R#L127
https://github.com/pbs-assess/gfplot/blob/master/R/pbs2mse.R#L190-L206

It must be getting fit for you without any or enough data. I'll dig in later. We don't need those standard errors, but we did want them for the P Cod assessment.

**Comment by andrew-edwards** [comment]
Thanks. Working now, latest version of gfplot/master. It's working through the remaining sculpins. I think the sculpins are generally bad news. I'll close if it builds.

**Comment by andrew-edwards** [comment]
Success! 273 pages of synopsis-y goodness....
