### ISSUE TITLE
Set two species codes back again when figure out why it breaks

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/gfsynopsis#50]
california grenadier is 257
deacon rockfish is 429

Have set these both to NA else I get the error
```
x Building figure pages for california grenadier
Fitting model for the survey SYN QCS
Interpolating depth to fill in missing data if needed...
Preloading interpolated depth for prediction grid...
Error: $ operator is invalid for atomic vectors
 ```
which we thought would be fixed by Sean's 998431.

Am pushing my commits now - have it working okay.

**Comment by seananderson** [comment]
Are those new species? Will need a `traceback()` to know much more. If you've added new species, something else might have broken unrelated to the geostat stuff. Can help later. Just changed how the geostat data is read in.

**Comment by andrew-edwards** [comment]
That's what I thought. Dont' worry for now - it's these minor species anyway. 

My .pdf now seems to building into _book/  , it had always been in report-rmd/.  I think I ran it the same way (the script in the makefile).  That may have confused me. Done now (prob for the night)....
