### ISSUE TITLE
Many of the survey references need to be fixed

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfsynopsis#51]
E.g. QCS: https://www.pac.dfo-mpo.gc.ca/od-ds/science/ground-fond/sbts/survey-summaries-sommaires-des-relev%C3%A9s-QCS-BRC-pac-dfo-mpo-science.html

The authors are often out of order (because they were out of order in one of the CSAS spreadsheets, I know) and sometimes there are more recent versions of the reports. E.g. QCS has a 2013 report instead of 2011. Have we really not published any of the reports since 2013?

**Comment by elisekeppel** [comment]
A few 2015 ones have recently been published (2018) - I will update these
