### ISSUE TITLE
Sean to fetch new gfsynopsis branch (but not quite yet).....

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/gfsynopsis#53]
Similarly to  https://github.com/pbs-assess/gfplot/issues/50    (and do both at same time).

I created a new branch   `merge-from-master` by the following:
```
git co master
git cb merge-from-master      [create dummy master to test the merge]
git merge get-iphc   [my development branch, but, unlike gfplot, there have been lots of commits hto gfynsopsis/master since I merged master into get-iphc]
```

So rather than pull all my changes into `master`, it seems safer if Sean fetches my merge-from-master branch and check the package builds okay. 

Maybe hold off until I've rebuilt all the figures with the `merge-from-master` version of each repo. If anything breaks I should be able to fix. May leave figures building overnight.

**Comment by andrew-edwards** [comment]
@seananderson - you could try and get both my `merge-from-master` branches (one from each repo) tonight and try building (like I'm doing in the notes above) if you want to leave it for a couple of hours to run. Mines building figures at about a minute per species.

**Comment by andrew-edwards** [comment]
Figure pages build (about 1 min per species), though it does print (to the console):
```
[1] "@galluci2011dogfish"
[1] "@king2015biglongnoseskate"
[1] "@king2015biglongnoseskate"
[1] "@forrest2015pcod"
[1] "@starr2017pollock"
...
```
now. Haven't checked if they appear okay in the document yet.

**Comment by seananderson** [comment]
Yes, I accidentally left a `print()` statement in there. I removed it last night. You can always open multiple consoles, set `N <- 1:10` or whatever, and source the script if you want to run multiple at once.

**Comment by andrew-edwards** [comment]
Great. 
My  `bookdown::render_book('index.Rmd')` works until:

```
label: sdmTMB-spt-plot-spatiotemporal-effects (with options) 
List of 2
 $ fig.width: num 8
 $ fig.cap  : chr "Spatiotemporal random effect predictions from geostatistical spatiotemporal model for Pacific Cod in Queen Char"| __truncated__

  |............................................................     |  92%
  ordinary text without R code

  |............................................................     |  93%
label: sdmTMB-get-index
Quitting from lines 3574-3577 (resdoc.Rmd) 
Error in `$<-.data.frame`(`*tmp*`, "year", value = c(2003L, 2004L, 2005L,  : 
  replacement has 9 rows, data has 0
In addition: There were 50 or more warnings (use warnings() to see the first 50)
```

**Comment by andrew-edwards** [comment]
Updated package (plus it updated some dependencies). I hadn't deleted `knitr-cache-tex` so am doing that also (there were some old related files in there). Get to same error, 

```
  |............................................................     |  93%
label: sdmTMB-get-index
Quitting from lines 3574-3577 (resdoc.Rmd) 
Error in `$<-.data.frame`(`*tmp*`, "year", value = c(2003L, 2004L, 2005L,  : 
  replacement has 9 rows, data has 0
In addition: There were 50 or more warnings (use warnings() to see the first 50)

> traceback()
24: stop(sprintf(ngettext(N, "replacement has %d row, data has %d", 
        "replacement has %d rows, data has %d"), N, nrows), domain = NA)
23: `$<-.data.frame`(`*tmp*`, "year", value = c(2003L, 2004L, 2005L, 
    2007L, 2009L, 2011L, 2013L, 2015L, 2017L))
22: `$<-`(`*tmp*`, "year", value = c(2003L, 2004L, 2005L, 2007L, 
    2009L, 2011L, 2013L, 2015L, 2017L))
21: get_index(predictions, bias_correct = FALSE)
20: eval(expr, envir, enclos)
```
Hopefully get fixed when I put new files in the right place....

**Comment by andrew-edwards** [comment]
Okay - mine builds now (except minor git calling issue). `knitr-cache-tex` all got rebuilt today. 

So I think you're good to fetch both of my `merge-from-master` branches (one in each repo).

**Comment by seananderson** [comment]
All merged!
