### ISSUE TITLE
Some references should be 'in press'

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/gfsynopsis#55]
Some of the references that have dates should really be 'in press', as the publication year isn't finalised yet. Though not ideal, for simplicity and speed we could leave the names the same (keppel2018yelloweye etc.), and just put    year = {in press}.

I can do it and test it (later in the week)....

e.g.

@article{keppel2018yelloweye,
  author  = {Keppel, E. A. and Olsen, N.},
  year    = {2018},
  title   = {{Pre-COSEWIC} review of {Yelloweye Rockfish} ({\emph{Sebastes
             ruberrimus}}) along the {Pacific} coast of {Canada}: biology,
             distribution and abundance trends},
  journal = {DFO Can. Sci. Advis. Sec. Res. Doc.},
  volume  = {2018/xxx},
  pages   = {}
}

@article{starr2017pollock,
  author  = {Paul J. Starr and Rowan Haigh},
  year    = {2017},
  title   = {{Walleye Pollock} ({\emph{Theragra chalcogramma}}) stock assessment
             for {British Columbia} in 2017},
  journal = {DFO Can. Sci. Advis. Sec. Res. Doc.},
  volume  = {2017/xxx},
  pages   = {}
}

**Comment by andrew-edwards** [comment]
Just spotted dfo2018pollock  is:
@article{dfo2018pollock,
  author  = {{Fisheries and Oceans Canada}},
  year    = {In press},
  title   = {{Walleye Pollock} ({\emph{Theragra chalcogramma}}) stock assessment
             for {British Columbia} in 2017},
  journal = {DFO Can. Sci. Advis. Sec. Sci. Advis. Rep.},
  volume  = {2018/xxx},
  pages   = {}
}

[though 'in press' gets referenced better than 'In press' in the text]

**Comment by seananderson** [comment]
Yes, I had to figure this out first. https://github.com/pbs-assess/gfsynopsis/commit/2db87554b75ae1359bd9d9fa9868e63b37019309

**Comment by andrew-edwards** [comment]
Fancy. I was just going to change the dates to 'in press' like I normally do....
Does it work? We need to take out the years in the .bib also.

**Comment by seananderson** [comment]
Before it left them as 'n. d.' (abbreviation of 'no date') which is why I had entered a date. Yes it works now. To get 'In press', it doesn't matter what you put in the year field as long as it is not a number. I think you can also remove the year field entirely. Thankfully csl is much easier to edit than bst and this made it easy to figure out what to change: http://editor.citationstyles.org/visualEditor/

**Comment by andrew-edwards** [comment]
Great. What about the .bib names. I guess for now we can leave as is (e.g. dfo2018pollock, though dfoInPresspollock would be more consistent) - it was just a little confusing  that Yelloweye had a 2015 label (as that when assessment was done), but was published after Redbanded that had a 2017 label (just confusing when ordering them in text). No big deal - can maybe tidy up after submitting.

**Comment by andrew-edwards** [comment]
Yes, leave for now
