### ISSUE TITLE
It can be helpful to have footers that refer to the section or appendix (not crucial though)

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/gfsynopsis#56]
For example, we had   Redbanded Rockfish   bottom left throughout that assessment, and `Appendix A - Catch Data' etc. in the bottom right. (I like to have a year also, for when looking at multiple assessments of the same species and not getting confused).

For this one, maybe:

gfsynopsis 2018                                        Appendix X ....

and for the main text maybe the section headings?  Or for the main figure pages, the species name in bottom right (useful for the second page of each) - presumably make-pages?

Also handy when editing. I can look into it if time (and no big deal - it's a want not a need). I know with latex we had to be careful that the Appendix ones ended up on the correct pages. 

Sorry, this got a bit longer than intended once I started thinking about it.

**Comment by seananderson** [comment]
I didn't realize this was allowable CSAS format, but yes, that would be nice. The exact same code you used for redbanded rockfish should work here as well. If you can point me to that I can try splicing it into the .tex or .sty file. I assume you're using fancyhdr or something like that.

**Comment by andrew-edwards** [comment]
Just randomly came across this (looking for something else), that might be useful (and looks similar to what we did in latex I think):

https://stackoverflow.com/questions/30922602/creating-a-footer-for-every-page-including-first-using-r-markdown

Sean - yes, they didn't allow it for a while but I kind of insisted. Yes, I think it's fancyhdr - the stuff may still be in the .sty file that we're using.

**Comment by andrew-edwards** [comment]
We can start page 1 with 1 (not i) for the working paper. I just checked with Ann. Avoids confusion in the meeting ('which page 175?') when people are using the .pdf....
