### ISSUE TITLE
This is in 02-plot-descriptions.Rmd - looks dangerous

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/gfsynopsis#57]
Is it okay to have this?

```{r install, eval=FALSE}
# install.packages("devtools")
devtools::install_github("pbs-assess/gfplot")
```

Likely confusing if developing a local gfplot and it installs the github version. Just wondering ...

**Comment by seananderson** [comment]
Old code. `eval = FALSE` so doesn't do anything.
