### ISSUE TITLE
Appendix Reference ref in list on page 9 still says H not I - I fixed in ToC.

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/gfsynopsis#67]
Not sure why 99-reference.Rmd says 'unnumbered' here:
 ```
<!--This manually sets the header for this unnumbered chapter.-->
\markboth{REFERENCES}{REFERENCES}
```

**Comment by seananderson** [comment]
Can't get it to work right now. I'm going to revert to an unlabelled chapter and I've adapted the text in the introduction appropriately.
