### ISSUE TITLE
Create french version of main pages

### ISSUE THREAD

**Issue by elisekeppel** [pbs-assess/gfsynopsis#7]
- [ ] `ggtitle()`s
- [ ] text at top
- [ ] maturity grouping labels
- [ ] axis labels
- [ ] gear labels

**Comment by andrew-edwards** [comment]
We should try out Rowan's `linguaFranca()` function:

https://github.com/pbs-software/pbs-tools/blob/master/PBStools/R/M01_Utility.r

The actual function starts on line 1007, with (lots of!) translated words/phrases going from 1026   to 1259.

Bascially, lines such as

`gsub("[Aa]pr", "avr",`

substitute Apr or apr [April] for avr.

Rowan creates the French figures with the same figure names in a subdirecory called "french", and just imports with

`\graphicspath{{\Sexpr{paste0(mpd.dir,ifelse(lang=="f","/french/","/"))}}}`

We'd need something similar in Rmarkdown. Or maybe just a parallel document with a switch at the start to say french. Am thinking we should get the Rmarkdown main text translated (which has minimal formatting words that they'd have to ignore), and then we rebuild the whole .pdf. Can discuss at the TTT workshop and see what the bilingual Gulf Region does.
