### ISSUE TITLE
Exclude unusable sets from length and age frequency plots

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfsynopsis#72]

**Comment by elisekeppel** [comment]
Perhaps also add in 'sorted' samples for length at age and age at maturity plots?

**Comment by seananderson** [comment]
@elisekeppel , can you remind me what I have to filter on for this? Is the relevant column already in the data?

**Comment by elisekeppel** [comment]
Yes, usability codes 1, 2 and 6  = "all data useable". Code 0 is 'unknown' and would be a judgement call. I believe I've seen code 0 included in Norm's code (no news is good news).

**Comment by seananderson** [comment]
Done
