### ISSUE TITLE
Include a shaded outline of the entire historical fishery extent

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/gfsynopsis#88]
(as in EOO for pre-COSEWIC)

Could be lightly shaded hexagons or could be a true polygon outline.

**Comment by seananderson** [comment]
@elisekeppel , can you deal with this on the SQL side first? Right now the minimum year is hardcoded into the SQL. E.g. 2012 for trawl. Maybe add an option to the get function to control the minimum year?

**Comment by elisekeppel** [comment]
Ok, did that for the sql side and added argument in plot-cpue-map. Still need to branch off within that function to keep the earlier years in for the historic extent layer.

**Comment by seananderson** [comment]
Awesome, thanks. I'll hopefully integrate that into the maps tomorrow when I'm back at PBS and can re-extract the data.

**Comment by seananderson** [comment]
I wonder if the privacy rule needs to be applied separately to the historical and post-footprint data sets or if it can be applied to the entire data set at once.
